--sql_006_OLIST_CASE_6

WITH CTE_ATIVO AS (
    SELECT  
        *,
        CASE
            WHEN VALOR_VENDA>0 THEN 1
        ELSE 0
        END AS ATIVO
    from planilha1
),
CTE_ATIVO_LAG AS (
    SELECT
        *,
        LAG(ATIVO) OVER (PARTITION BY seller_id ORDER BY MES_REFERENCIA ASC) AS ATIVO_LAG
    from CTE_ATIVO
)

SELECT
    *,
    CASE
        WHEN MES_PRIMEIRA_VENDA>MES_REFERENCIA THEN 'PRIOR ENTRY'
        WHEN MES_PRIMEIRA_VENDA=MES_REFERENCIA THEN 'NOVO'
        WHEN ATIVO=1 AND ATIVO_LAG=1 THEN 'REGULAR'
        WHEN ATIVO=0 THEN 'CHURN'
        WHEN ATIVO=1 AND ATIVO_LAG=0 THEN 'RECUPERADO'

    END AS CLASSIFICACAO
FROM CTE_ATIVO_LAG